/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CreateButton: typeof import('./src/components/_common/form/CreateButton.vue')['default']
    FButton: typeof import('./src/components/_common/form/FButton.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputError: typeof import('./src/components/_common/form/InputError.vue')['default']
    InputField: typeof import('./src/components/_common/form/InputField.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftMenu: typeof import('./src/components/_layout/LeftMenu.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MobileMenu: typeof import('./src/components/_layout/MobileMenu.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveButton: typeof import('./src/components/_common/form/SaveButton.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    TextField: typeof import('./src/components/_common/form/TextField.vue')['default']
    TheButton: typeof import('./src/components/_common/form/TheButton.vue')['default']
    UpdateButton: typeof import('./src/components/_common/form/UpdateButton.vue')['default']
    UserProfileMenu: typeof import('./src/components/_layout/topbar/UserProfileMenu.vue')['default']
  }
}
